#include "menufield.h"

menufield::menufield(QWidget *parent) : QMainWindow(parent)
{
    setWindowIcon(QIcon(QStringLiteral(":/new/cards/field/gwent.ico")));

    scene = new QGraphicsScene();
    scene->setSceneRect(0, 0, FIELD_WIDTH*SCALE_FILED_WINDOW, FIELD_HEIGHT*SCALE_FILED_WINDOW);

    field = new Field(address_menufield, scene);
    scene->addItem(field);

    view = new QGraphicsView(scene);
    view->resize(FIELD_WIDTH*SCALE_FILED_WINDOW, FIELD_HEIGHT*SCALE_FILED_WINDOW);
    view->show();

    btn_game = new QPushButton(parent);
    btn_deck_A = new QPushButton(parent);
    btn_deck_B = new QPushButton(parent);
    btn_exit = new QPushButton(parent);
    btn_game->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_A->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_B->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_exit->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_game->setStyleSheet("QPushButton{border-image:url(:/new/cards/field/game.jpg);" "border:2px 2px 2px 2px;}");
    btn_deck_A->setStyleSheet("QPushButton{border-image:url(:/new/cards/field/deck_A.jpg);" "border:2px 2px 2px 2px;}");
    btn_deck_B->setStyleSheet("QPushButton{border-image:url(:/new/cards/field/deck_B.jpg);" "border:2px 2px 2px 2px;}");
    btn_exit->setStyleSheet("QPushButton{border-image:url(:/new/cards/field/exit.jpg);" "border:2px 2px 2px 2px;}");

    scene->addWidget(btn_game);
    scene->addWidget(btn_deck_A);
    scene->addWidget(btn_deck_B);
    scene->addWidget(btn_exit);

    connect(btn_game, SIGNAL(clicked(bool)), this, SLOT(btnMoveOut1()));
    connect(btn_deck_A, SIGNAL(clicked(bool)), this, SLOT(btnMoveOut2()));
    connect(btn_deck_B, SIGNAL(clicked(bool)), this, SLOT(btnMoveOut3()));
    connect(btn_exit, SIGNAL(clicked(bool)), this, SLOT(btnMoveOut4()));
}

void menufield::createBattle()
{
    battle = new BattleField(address_save, address_save_2);
    btn_game->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_A->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_B->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_exit->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
}

void menufield::createSelectA()
{
    select = new SelectScene(address_save);
    btn_game->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_A->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_B->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_exit->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
}

void menufield::createSelectB()
{
    select = new SelectScene(address_save_2);
    btn_game->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_A->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_deck_B->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
    btn_exit->setGeometry(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW,
                         ICON_WIDTH*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW, ICON_HEIGHT*SCALE_MENUFIELD_BUTTON*SCALE_FILED_WINDOW);
}

void menufield::btnMoveOut1()
{
    QPropertyAnimation *animation1 = new QPropertyAnimation(btn_game, "pos");
    animation1->setDuration(ANI_TIME);
    animation1->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation2 = new QPropertyAnimation(btn_deck_A, "pos");
    animation2->setDuration(ANI_TIME);
    animation2->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation3 = new QPropertyAnimation(btn_deck_B, "pos");
    animation3->setDuration(ANI_TIME);
    animation3->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation4 = new QPropertyAnimation(btn_exit, "pos");
    animation4->setDuration(ANI_TIME);
    animation4->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));

    QAnimationGroup *group = new QParallelAnimationGroup(this);
    group->addAnimation(animation1);
    group->addAnimation(animation2);
    group->addAnimation(animation3);
    group->addAnimation(animation4);

    group->start();
    connect(group, SIGNAL(finished()), this, SLOT(createBattle()));
}

void menufield::btnMoveOut2()
{
    QPropertyAnimation *animation1 = new QPropertyAnimation(btn_game, "pos");
    animation1->setDuration(ANI_TIME);
    animation1->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation2 = new QPropertyAnimation(btn_deck_A, "pos");
    animation2->setDuration(ANI_TIME);
    animation2->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation3 = new QPropertyAnimation(btn_deck_B, "pos");
    animation3->setDuration(ANI_TIME);
    animation3->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation4 = new QPropertyAnimation(btn_exit, "pos");
    animation4->setDuration(ANI_TIME);
    animation4->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));

    QAnimationGroup *group = new QParallelAnimationGroup(this);
    group->addAnimation(animation1);
    group->addAnimation(animation2);
    group->addAnimation(animation3);
    group->addAnimation(animation4);

    group->start();
    connect(group, SIGNAL(finished()), this, SLOT(createSelectA()));
}

void menufield::btnMoveOut3()
{
    QPropertyAnimation *animation1 = new QPropertyAnimation(btn_game, "pos");
    animation1->setDuration(ANI_TIME);
    animation1->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation2 = new QPropertyAnimation(btn_deck_A, "pos");
    animation2->setDuration(ANI_TIME);
    animation2->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation3 = new QPropertyAnimation(btn_deck_B, "pos");
    animation3->setDuration(ANI_TIME);
    animation3->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation4 = new QPropertyAnimation(btn_exit, "pos");
    animation4->setDuration(ANI_TIME);
    animation4->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));

    QAnimationGroup *group = new QParallelAnimationGroup(this);
    group->addAnimation(animation1);
    group->addAnimation(animation2);
    group->addAnimation(animation3);
    group->addAnimation(animation4);

    group->start();
    connect(group, SIGNAL(finished()), this, SLOT(createSelectB()));
}

void menufield::btnMoveOut4()
{
    QPropertyAnimation *animation1 = new QPropertyAnimation(btn_game, "pos");
    animation1->setDuration(ANI_TIME);
    animation1->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));
    animation1->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW, MENUFIELD_1_TOP*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation2 = new QPropertyAnimation(btn_deck_A, "pos");
    animation2->setDuration(ANI_TIME);
    animation2->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));
    animation2->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation3 = new QPropertyAnimation(btn_deck_B, "pos");
    animation3->setDuration(ANI_TIME);
    animation3->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));
    animation3->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V_2*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*2)*SCALE_FILED_WINDOW));

    QPropertyAnimation *animation4 = new QPropertyAnimation(btn_exit, "pos");
    animation4->setDuration(ANI_TIME);
    animation4->setStartValue(QPoint(MENUFIELD_BUTTON_LEFT*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.2, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.4, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*2)*SCALE_FILED_WINDOW, (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.6, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*3)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setKeyValueAt(0.8, QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*4)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));
    animation4->setEndValue(QPoint((MENUFIELD_BUTTON_LEFT+MENUFIELD_V*5)*SCALE_FILED_WINDOW,  (MENUFIELD_1_TOP+MENUFIELD_S*3)*SCALE_FILED_WINDOW));

    QAnimationGroup *group = new QParallelAnimationGroup(this);
    group->addAnimation(animation1);
    group->addAnimation(animation2);
    group->addAnimation(animation3);
    group->addAnimation(animation4);

    group->start();
    connect(group, SIGNAL(finished()), view, SLOT(close()));
}
